import Image from 'next/image'
import Link from 'next/link'
import { Container, Row, Col, Accordion, Tab, Tabs } from 'react-bootstrap';

export const Faq = (props) => {
    return (
        <div className='faqRow'>
            <div className="tabContentsOuter">
                <Tabs
                    defaultActiveKey="socialMedia"
                    id="uncontrolled-tab-example"
                >
                    <Tab
                        eventKey="socialMedia"
                        title={<>Minimum Investment Amount?</>}
                    >
                        <div className='tabContentDiv'>
                            <Row>
                                <Col lg={12}>
                                    <div className='tabContentInfo'>
                                        <h3>Minimum Investment Amount?</h3>
                                        <p>The minimum investment amount for properties on our platform varies based on the Offering. However, you can invest in a fraction of a property for as little as $25. We understand that real estate investing can be a big step for some individuals, especially those who are new to the process or have limited funds. That&apos;s why we strive to provide accessible options for all types of investors, regardless of their financial situation. By keeping our minimum investment amount low, we hope to make the process as easy and accessible as possible for everyone interested in investing in real estate. It allows more people to have the chance to invest in properties they might not be able to purchase on their own, and it allows them to diversify their investment options in the real estate market. With a low barrier of entry, we believe that more people will be able to experience the benefits of real estate investing and reap the rewards in the long run.</p>
                                    </div>
                                </Col>
                            </Row>
                        </div>
                    </Tab>
                    <Tab
                        eventKey="Who pays for maintenance expenses?"
                        title={<>Who pays for maintenance expenses?</>}
                    >
                        <div className='tabContentDiv'>
                            <Row>
                                <Col lg={12}>
                                    <div className='tabContentInfo'>
                                        <h3>Who pays for maintenance expenses?</h3>
                                        <p>The maintenance expenses for the properties on our platform are primarily the responsibility of the property owners. However, as a way to ensure that properties are well-maintained and to protect the interests of our investors, we require all properties to be funded with a 5% operational expense reserve for maintenance. Additionally, 5% of the cash flow generated by each property every month is allocated towards the maintenance reserve. This way, we can ensure that any necessary repairs or maintenance are taken care of in a timely manner and that the properties continue to generate income for our investors. We understand that the maintenance of the properties is crucial to the success of the investments, and we strive to make it as seamless and stress-free as possible for our users.</p>
                                    </div>
                                </Col>
                            </Row>
                        </div>
                    </Tab>
                    <Tab
                        eventKey="Do I need to be accredited to invest??"
                        title={<>Do I need to be accredited to invest?</>}
                    >
                        <div className='tabContentDiv'>
                            <Row>
                                <Col lg={12}>
                                    <div className='tabContentInfo'>
                                        <h3>Do I need to be accredited to invest?</h3>
                                        <p>Investing in real estate through our platform does not require accreditation, unlike traditional real estate investment options. This is thanks to the concept of fractional ownership, which allows for more affordable entry into the market and enables investors to share risks and responsibilities. This makes it a more accessible and secure investment option for a wider range of individuals.</p>
                                    </div>
                                </Col>
                            </Row>
                        </div>
                    </Tab>
                    <Tab
                        eventKey="How often are dividends sent to holders?"
                        title={<>How often are dividends sent to holders?</>}
                    >
                        <div className='tabContentDiv'>
                            <Row>
                                <Col lg={12}>
                                    <div className='tabContentInfo'>
                                        <h3>How often are dividends sent to holders?</h3>
                                        <p>Dividends are typically paid out on a monthly basis to holders of our fractional property investments. These payments are calculated based on the net cash flow of the property and distributed according to the percentage of ownership held by each investor. Additionally, we provide transparent and regular updates on the financial performance of each property, allowing our investors to stay informed and track the performance of their investment. We also have a dedicated team available to answer any questions and provide support throughout the investment process, ensuring that our investors feel confident and informed every step of the way.</p>
                                    </div>
                                </Col>
                            </Row>
                        </div>
                    </Tab>
                    <Tab
                        eventKey="website"
                        title={<>What are my tax obligations?</>}
                    >
                        <div className='tabContentDiv'>
                            <Row>
                                <Col lg={12}>
                                    <div className='tabContentInfo'>
                                        <h3>What are my tax obligations?</h3>
                                        <p>Investing in fractional real estate can have tax implications, just like any other type of investment. However, the specifics of your tax obligations will depend on your individual circumstances and should be discussed with a tax professional. In general, any income received from the investment, such as rental income or capital gains from the sale of the property, will be subject to taxation. Additionally, you may be eligible for certain tax benefits, such as deductions for mortgage interest, depreciation of the property, or 1031 exchanges. It&apos;s important to keep accurate records and consult with a tax advisor to understand your specific obligations and take advantage of any potential tax benefits.</p>
                                    </div>
                                </Col>
                            </Row>
                        </div>
                    </Tab>
                </Tabs>
            </div>
        </div>
    )
}